# docker-compose.template.yml
version: '3.8'
services:
  site:
    image: faelsouz/findfruit:cee9ec13afa66cecd1956f6c03f1861f6356cf48
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.findfruit.rule=Host(`findfruit.com.br`) || Host(`www.findfruit.com.br`)"
        - "traefik.http.routers.findfruit.entrypoints=websecure"
        - "traefik.http.routers.findfruit.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.findfruit.loadbalancer.server.port=80"
    networks:
      - network_public

networks:
  network_public:
    external: true
