version: '3.8'

services:
  site:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Regra para acessar pelos dois domínios (sem erro de sintaxe)
        - "traefik.http.routers.findfruit.rule=Host(`findfruit.com.br`) || Host(`www.findfruit.com.br`)"

        # Entrypoint seguro (HTTPS)
        - "traefik.http.routers.findfruit.entrypoints=websecure"

        # Resolver do TLS (Let's Encrypt)
        - "traefik.http.routers.findfruit.tls.certresolver=letsencryptresolver"

        # Porta interna exposta no container (nginx serve na 80)
        - "traefik.http.services.findfruit.loadbalancer.server.port=80"

    volumes:
      - ./dist:/usr/share/nginx/html:ro

    networks:
      - network_public

networks:
  network_public:
    external: true
