# Arquivo: prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  # ... outras configurações para prometheus, cadvisor, node_exporter ...

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Usa o módulo definido no blackbox-config.yml
    static_configs:
      - targets:
        - https://findfruit.com.br
        - https://api.sugestaodevendas.com.br
        - https://sysapi.facebook.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # ESTA É A LINHA INCORRETA QUE VOCÊ PROVAVELMENTE TEM:
        # replacement: 'observability_blackbox:9115'
        #
        # ESTA É A LINHA CORRETA QUE VOCÊ PRECISA USAR:
        replacement: 'blackbox:9115'