name: CI/CD Deploy FindFruit

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Image Tag
        id: meta
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/findfruit:latest
            ${{ secrets.DOCKER_USERNAME }}/findfruit:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-server:
    name: Deploy to Server via SSH
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            echo "Deploying tag: $IMAGE_TAG"
            cd /var/www/findfruit
            sed -i "s|image: .*$|image: ${DOCKER_USERNAME}/findfruit:${IMAGE_TAG}|" docker-compose.yml
            docker-compose pull
            docker-compose up -d
            docker stack deploy -c docker-compose.yml findfruit
            docker system prune -f -a --volumes --force
